In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import transformers as ppb 

In [2]:
# DistilBERT
model_class = ppb.TFDistilBertModel
tokenizer_class = ppb.DistilBertTokenizer
pretrained_weights = 'distilbert-base-uncased'

#BERT
#model_class = ppb.TFBertModel
#tokenizer_class = ppb.BertTokenizer
#pretrained_weights = 'bert-base-uncased'


model = model_class.from_pretrained(pretrained_weights)
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)



Some layers from the model checkpoint at distilbert-base-uncased were not used when initializing TFDistilBertModel: ['vocab_projector', 'vocab_layer_norm', 'activation_13', 'vocab_transform']
- This IS expected if you are initializing TFDistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFDistilBertModel were initialized from the model checkpoint at distilbert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [22]:
text = "Replace me by any text you'd like."

encoded_text = tokenizer(text, return_tensors='tf')
#encoded_text = tokenizer(text)
encoded_text

{'input_ids': <tf.Tensor: shape=(1, 12), dtype=int32, numpy=
array([[ 101, 5672, 2033, 2011, 2151, 3793, 2017, 1005, 1040, 2066, 1012,
         102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [23]:
tokenizer.decode(encoded_text['input_ids'][0])

"[CLS] replace me by any text you'd like. [SEP]"

In [24]:
encoded_text['input_ids']
output = model(encoded_text)


In [25]:
output.last_hidden_state.shape # Embedding

TensorShape([1, 12, 768])

In [26]:
pipeline = ppb.pipeline
unmasker = pipeline('fill-mask', model=pretrained_weights)
#unmasker(["children play in the [MASK].", "boy play in the [MASK].", "girl play in the [MASK]."])
#unmasker("[MASK] Allan Poe.")
unmasker("In a year, there are [MASK] months in which [MASK] is the first.")


[[{'score': 0.08231750130653381,
   'token': 2416,
   'token_str': 'six',
   'sequence': '[CLS] in a year, there are six months in which [MASK] is the first. [SEP]'},
  {'score': 0.07331888377666473,
   'token': 2176,
   'token_str': 'four',
   'sequence': '[CLS] in a year, there are four months in which [MASK] is the first. [SEP]'},
  {'score': 0.06642419844865799,
   'token': 2698,
   'token_str': 'seven',
   'sequence': '[CLS] in a year, there are seven months in which [MASK] is the first. [SEP]'},
  {'score': 0.061364300549030304,
   'token': 2093,
   'token_str': 'three',
   'sequence': '[CLS] in a year, there are three months in which [MASK] is the first. [SEP]'},
  {'score': 0.04870373755693436,
   'token': 4376,
   'token_str': 'twelve',
   'sequence': '[CLS] in a year, there are twelve months in which [MASK] is the first. [SEP]'}],
 [{'score': 0.09364783763885498,
   'token': 7114,
   'token_str': 'autumn',
   'sequence': '[CLS] in a year, there are [MASK] months in which autu